root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/web"
  bin = "./tmp/main"
  include_ext = ["go", "html", "css", "js", "svg"]
  include_dir = ["cmd", "internal"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
